### ISSUE TITLE
Parsing ExpressionStatement

### ISSUE THREAD

**Issue by djn3m0** [austinbyers/esprima-ast-visitor#3]
Hi,
First of all I should thank you for accepting my feature request. :-)
Its all good and working, the current problem I have right now is 'Parsing ExpressionStatement'!

The problem is that ExpressionStatements could have another kind of Expression or Statement in them, how can I parse them and find which Expression or Statement does it contain?

What am I trying to achieve?

Im trying to parse the target code when some specific conditions met, add a ExpressionStatement... so far so good. But before adding the ExpressionStatement I need to check for the dependency of that Expression, for example:
var test= 10;
afunction(1, "a", test);

I need to that 'test' is a dependency of afunction, so in order to make afunction work i need to add 'test' variable too.
I hope im clear enough, the whole idea is how to check for dependency of an expression? and as return get the ast node of each of those dependencies?

Thank you

**Comment by austinbyers** [comment]
Trying to determine dependencies statically is a much harder problem. In fact, it's impossible in the general case (courtesy of the halting problem). For example, suppose we have a variable

```js
var map = {'abc': 123}
```

The following expressions are all equivalent:
```js
map
window["map"]
window["m" + "a" + "p"]
eval('map')
```

Assuming that there are no degenerate cases like this, you could probably build something that looks for those dependencies. But the AST generated by Esprima has no knowledge of dependencies. When it sees `afunction(1, "a", test)` it just sees `ExpressionStatement(Int, String, Identifier)`. It doesn't know what that identifier refers to.

You'd have to build your own lookup logic for that, or else there may be other JavaScript projects with that capability.

**Comment by djn3m0** [comment]
I already had some tries, for example i keep all global and local variables in separate lists then if i see a Variable in an Expression I will check those two list to find out, but as I said an ExpressionStmt can get verryy complex like "afunction(alocalvar, another_function(new Object(another_var), {'abc': 123}...)"!

What i think as a solution is to have ExpressionStatement visitor, with same principle as the normal node visitor, that can take an ExpressionStatement as a parameter and we can check 'type' of each node inside the ExpressionStatement, I dont know how much what I said is possible?

**Comment by austinbyers** [comment]
The entire nested structure can actually be visited. Every `Node` subclass includes a list of `fields` representing each of its child Nodes. For example,

```js
var map = {'abc': 123}
```

will be parsed as

```
Program
    .body: [VariableDeclaration]
        .declarations: [VariableDeclarator]
            .id: Identifier
                .name: "map"
            .init: ObjectExpression
                .properties: [Property]
                    .key: Literal
                        .value: "abc"
                    .value: Literal
                        .value: 123
```

So, for example, you could grab and modify the ObjectExpression like this:

```python
ast = json.loads(esprima_ast_string)
program = visitor.objectify(ast)  # visitor.Node object

object_exp = program.body[0].declarations[0].init  # ObjectExpression
print(object_exp.fields)  # ['properties']
object_exp.properties[0].key.value = "new-key"

# At this point, the AST is now equivalent to the following JS code:
# var map = {'new-key': 123}
```

Does this help? I'll update the top-level README as well

**Comment by djn3m0** [comment]
Interesting...
And from here on:
```
xpr_list= []
ast = json.loads(esprima_ast_string)
program = visitor.objectify(ast)  # visitor.Node object
for node in program.traverse():
    if node.type == 'ExpressionStatement':
        xpr_list.append(node)
``` 
can i do like :
```
a_node = xpr_list[0]
for node in a_node.traverse():
    print(node.type)
```
?
Because the whole question is to being able to visit an specific ExpressionStatement.

Thank you 👍

**Comment by austinbyers** [comment]
Yes, you've got it! It works exactly as you've described.

Keep in mind that an `ExpressionStatement` may itself include many embedded `ExpressionStatement` objects. So your `xpr_list` will include all `ExpressionStatement` nodes, even those which are embedded within others.

**Comment by djn3m0** [comment]
Amazing. This solved and old problem in a clean way. :)

**Comment by austinbyers** [comment]
Great, happy to help!
